---
- name: Deploy Site-B
  hosts: siteb
  become: yes

  tasks:
  - name: install docker preqequisities
    pip:
      name: docker

  - name: launch the apache-simple container on the site-b nodes
    docker_container:
      name: apache-simple
      image: quay.io/jvdst1/ansible-for-devops-siteb5
      ports:
        - "8080:8080"

